### ISSUE TITLE
bunker sprites (feste bunker am unteren spielfeldrand die zerstoerbar sind)

### ISSUE THREAD

**Issue by majacal** [oliverhuckfeldt/pattframe#16]
## todo:

- [ ] images generieren ...

- [ ] loop zum konstuieren der bunker

- [ ] loop zum aufstellen der bunker

- [ ] in kevin seine logik implementieren

- [ ] collision detection

## comment:

notation like kevins beweglichen invaders:
```
| matthias@MatthiasMacbookPro ~/IdeaProjects/pattframe (aspecialkey_dev)*$
| => ll playground_kevin/spaceinvaders/resources/images/
total 36
-rw-r--r--  1 matthias  staff   1,6K  8 Dez 07:59 beuth-logo.png
-rw-r--r--  1 matthias  staff   142B  8 Dez 07:59 bullet.png
-rw-r--r--  1 matthias  staff   298B  8 Dez 07:59 invader1a.png
-rw-r--r--  1 matthias  staff   282B  8 Dez 07:59 invader1b.png
-rw-r--r--  1 matthias  staff   356B  8 Dez 07:59 invader2a.png
-rw-r--r--  1 matthias  staff   355B  8 Dez 07:59 invader2b.png

```

1a 1b 1c 1d 1e
2a 2b 2c 2d 2d

a = volle pixel (intakt)
b = 75% pixel
c = 50% pixel
d = 25% pixel
e = 0 pixel (zerstoert)

ein bunker besteht aus
bunker = 1 +2 +3 ... 

es gibt 4 bunker am unteren spielrand oberhalb der spielfigur

**Comment by majacal** [comment]
hilfreich:
http://www.pixelartor.com/

evtl gibs auch imagemagick pixelgenerator

**Comment by majacal** [comment]
@aspecialkey 
https://github.com/oliverhuckfeldt/pattframe/commit/4924742853482b5c4c7ada7fc38e82fbc8926350
https://github.com/oliverhuckfeldt/pattframe/commit/d6f2c76a01126db9f90231c388a13b363f384243
https://github.com/oliverhuckfeldt/pattframe/commit/f1d162999565cd693af2ff7cb48546e0811ab107

schau mal ob die bilder so passen ich wusste nicht welche aufloesung muss man ausprobieren ... das resizen ist ja mit beigelegten shellscript kein problem

- habe jetzt erstmal 8x8 16x16 u 32x32 gemacht

1 = vollausgefuelltes 
2 = eine ecke

- die buchstaben fuer den demolition state (ecken haben nur 3 states weil halbe anzahl pixel)

- jeweils von unten bzw oben beschiessbar 

- zu den ecken kann man ja bei der einbindung sicherlich  nen rotation flag setzen ... oder die werden nochmal gespiegelt 


ich seh gerad das es auf der website gar nict anders aussieht wenn sie von oben oder von unten beschossen werden .. glaub das machen wir auch so oder ?


moeglicher bauplan:

```
1 = '='
2 = '+'

  +==========+
 +============+
====+      +====
====        ====
====        ====
====        ====


```

**Comment by aspecialkey** [comment]
schonmal rausbekommen, wie man die dinger speichern kann (in welchem
pfad - ich hab nirgends berechtigung ms-windows...)

Am 2016-12-11 19:31, schrieb Matthias Hertel:

> hilfreich:
> http://www.pixelartor.com/ 
> 
> evtl gibs auch imagemagick pixelgenerator 
> 
> --
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/oliverhuckfeldt/pattframe/issues/16#issuecomment-266298488
[2]

**Comment by majacal** [comment]
ja ich konnte speichern evtl liegt es am browser?

Von meinem iPhone gesendet

**Comment by aspecialkey** [comment]
achso haste schon gemacht... muss man halt weiterlesen und nicht nur
begeistert sein... 

Am 2016-12-11 21:02, schrieb Matthias Hertel:

> @aspecialkey [1]
> 4924742 [2]
> d6f2c76 [3]
> f1d1629 [4] 
> 
> schau mal ob die bilder so passen ich wusste nicht welche aufloesung muss man ausprobieren ... das resizen ist ja mit beigelegten shellscript kein problem 
> 
> * habe jetzt erstmal 8x8 16x16 u 32x32 gemacht
> 
> 1 = vollausgefuelltes
> 2 = eine ecke 
> 
> * 
> 
> die buchstaben fuer den demolition state (ecken haben nur 3 states weil halbe anzahl pixel) 
> * 
> 
> jeweils von unten bzw oben beschiessbar 
> * 
> 
> zu den ecken kann man ja bei der einbindung sicherlich nen rotation flag setzen ... oder die werden nochmal gespiegelt 
> 
> ich seh gerad das es auf der website gar nict anders aussieht wenn sie von oben oder von unten beschossen werden .. glaub das machen wir auch so oder ? 
> 
> moeglicher bauplan:
> 
> 1 = '='
> 2 = '+'
> 
> +==========+
> +============+
> ====+      +====
> ====        ====
> ====        ====
> ====        ====
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [5], or mute the thread [6].
 

Links:
------
[1] https://github.com/aspecialkey
[2]
https://github.com/oliverhuckfeldt/pattframe/commit/4924742853482b5c4c7ada7fc38e82fbc8926350
[3]
https://github.com/oliverhuckfeldt/pattframe/commit/d6f2c76a01126db9f90231c388a13b363f384243
[4]
https://github.com/oliverhuckfeldt/pattframe/commit/f1d162999565cd693af2ff7cb48546e0811ab107
[5]
https://github.com/oliverhuckfeldt/pattframe/issues/16#issuecomment-266303755
[6]

**Comment by majacal** [comment]
hehe - ja das konstruieren eines einzeln bunkers schaue ich morgen mal an


Von meinem iPhone gesendet
