### ISSUE TITLE
screen design - mocks der einzelnen screens

### ISSUE THREAD

**Issue by majacal** [oliverhuckfeldt/pattframe#18]
## vorbemerkungen:
wir haben im tagesprotokoll folgende screens festgehalten:

1. Willkommensscreen
2. Spielscreen (hier gameplay engine)
3. Highscore screen (hier datenbank blabla)

4. Credits (excluded from milestone "erste lauffaehige anwendung")
5. Settings (excluded from milestone "erste lauffaehige anwendung")

der ablauf ist nicht linear ... siehe issue spielablauf: #19 

## todo:
- [ ] screens entwerfen (hbox vbox der ganze schnurz keine ahnung wie ...einfach hier drueber diskutieren)

- [ ] app entwickeln um simple durch die screens zuschalten ? verknuepft mit spielablauf issue #19 

- [ ] mergen mit gameplay engine screen (so das wir ein runden "lauffaehigen" rudimentären ablauf haben

**Comment by majacal** [comment]
## 4. Views

wie das andere geloest haben ... 
https://www.youtube.com/watch?v=5GsdaZWDcdY
https://github.com/acaicedo/JFX-MultiScreen/tree/master/ScreensFramework/src/screensframework

multiple screens skeleton

### 4.1
willkommensscreen
 

### 4.2 
gameplayscreen


### 4.3 
highscorescreen

**Comment by majacal** [comment]
bootstrap
https://github.com/dicolar/jbootx

**Comment by markweigelt** [comment]
Der Willkommensscreen ist soweit fertig. Feintuning mit Abständen folgt noch später.
